debug:
  level: 10
  log_dir: ../logs
  logging_format: "[%(asctime)s - %(name)s - line %(lineno)s - %(levelname)s] %(message)s"
  summary_length: 100
format: 
  datetime: "%Y%m%d-%H:%M:%S,%2d"
  datetime_short: "%Y%m%d%H%M%S"
  datetime_file: "%y%m%d-%H%M%S"
  date: "%Y%m%d"
files:
  input_dir: ../data/input
  output_dir: ../data/output
  report_dir: ../data/report
  font-name: 'Times' 
translate:
  #options: google, aws, biotranscribe
  engine: aws 
  # model_dir is only needed when engine is biotranscribe
  model_dir: zh-en/20201120 
  # used to map language codes, see ./*_languages.py
  sourceLanguageCode: "zh-cn"
  targetLanguageCode: "en"
report:
  output_dir: ../data/report
aws:
  region: us-east-1